name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/actions/gradle-cache
    - name: Set up java
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
    - name: Build
      run: ./gradlew check --stacktrace --no-daemon
